#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
  systemctl disable --now antminer-fleet-tunnel.service >/dev/null 2>&1 || true
  systemctl disable --now antminer-fleet-server.service >/dev/null 2>&1 || true
fi
